import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const apiSidebar = require('./.docusaurus/api-sidebar-default-current');

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docs: [ { type: 'autogenerated', dirName: '.' } ],

    api: apiSidebar,

    community: [
        { type: 'autogenerated', dirName: '.' },
        {
            type: 'link',
            label: 'Serenity/JS Forum',
            href: 'https://github.com/orgs/serenity-js/discussions',
        },
        {
            type: 'link',
            label: 'Serenity/JS Chat',
            href: 'https://matrix.to/#/#serenity-js:gitter.im',
        }
    ],
};

export default sidebars;
