import { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { SidebarItemCategoryConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types';

function category(label: string, dirName: string): SidebarItemCategoryConfig {
    return {
        type: 'category',
        label,
        link: { type: 'doc', id: `${ dirName }/index` },
        collapsible: true,
        collapsed: true,
        items: [ { type: 'autogenerated', dirName } ]
    }
}

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docs: [
        {
            type: 'category',
            label: 'Introduction',
            link: { type: 'doc', id: 'index' },
            collapsible: true,
            collapsed: false,
            items: [
                'installation',
                'architecture',
                'project-templates',
            ]
        },
        {
            type: 'category',
            label: 'Tutorials',
            link: { type: 'doc', id: 'tutorials/index' },
            collapsible: true,
            collapsed: false,
            items: [
                { type: 'autogenerated', dirName: 'tutorials' }
            ]
        },
        {
            type: 'category',
            label: 'Integrations',
            collapsible: false,
            // link: { type: 'doc', id: 'integration/index' },
            items: [
                category('Test Runners', 'test-runners'),
                category('Reporting', 'reporting'),
                category('Software Delivery Tools', 'integration'),
            ]
        },
        {
            type: 'category',
            label: 'Design Patterns',
            collapsible: false,
            // link: { type: 'doc', id: 'design/index' },
            items: [
                category('Core Patterns', 'design'),
                category('Web Testing Patterns', 'web-testing'),
                category('API Testing Patterns', 'api-testing'),
                category('Mobile Testing Patterns', 'mobile-testing'),
            ],
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
