import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docs: [
        { type: 'autogenerated', dirName: '.' },
        {
            type: 'link',
            label: 'Release notes on GitHub',
            href: 'https://github.com/serenity-js/serenity-js/releases',
        },
        {
            type: 'link',
            label: 'Changelog on GitHub',
            href: 'https://github.com/serenity-js/serenity-js/blob/main/CHANGELOG.md',
        }
    ],
};

export default sidebars;
